{
 "title": "Live Webinar Playground",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "route",
    "label": "NYC Bus Route",
    "query": "SELECT k AS \"__text\", v AS \"__value\" from (values ('Manhattan','M'),('Bronx/Brooklyn' ,'B'),('Queens','Q'),('Staten Island','S')) v(k,v);"
   }
  ]
 },
 "panels": [
  {
   "title": "COVID 19 Spread in USA",
   "type": "graph",
   "description": "Plotting cases and deaths of COVID-19",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "-- Simple query to chart growth of cases and deaths due to COVID-19 over time\nSELECT date as \"time\", sum (cases) as total_cases, sum(deaths) as total_deaths\nFROM states\nGROUP BY time\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Real time location of NYC Busses",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 29, "w": 12, "x": 11, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  max(time) AS \"time\",\n  vid AS \"vehicle_id\",\n  route_id,\n  CASE WHEN route_id LIKE 'M%' THEN 1\n       WHEN route_id LIKE 'B%' THEN 2\n       WHEN route_id LIKE 'Q%' THEN 3\n       WHEN route_id LIKE 'S%' THEN 4\n       ELSE 0\n   END AS \"color\",\n  ST_X(geom) AS \"longitude\",\n  ST_Y(geom) AS \"latitude\"\nFROM mta \nWHERE time > now()-interval '1.5 minutes' AND substring(route_id,1,1) IN ($route)\ngroup by vid, route_id, geom order by 1;"
    }
   ]
  },
  {
   "title": "Timescale Version",
   "type": "singlestat",
   "description": "Version of Timescale on Taxi DB",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "-- What version of Timescale am I using?\nSELECT extversion FROM pg_extension WHERE extname='timescaledb';\n"
    }
   ]
  },
  {
   "title": "Current Cache hit ratio for TaxiDB",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 8 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "-- Cache Hit ratio\n-- hit = Blocks hit = number of disk block found already in the buffer cache s/t a read was not needed\n-- read = disk blocks read by data base\nSELECT hit.time, SUM(hit.value)/(SUM(hit.value) + SUM(read.value)) as cache_hit_rate\nFROM metrics_values hit \nINNER JOIN metrics_values read ON hit.time = read.time\nWHERE  hit.labels_id = 312 AND read.labels_id = 314\nGROUP BY hit.time\nORDER BY hit.time;"
    }
   ]
  },
  {
   "title": "Taxi DB Disk Used",
   "type": "gauge",
   "description": "Percentage disk used on Taxi DB",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "-- Disk usage\nSELECT\n  $__timeGroupAlias(\"time\", 1m),\n  avg(value) AS \"% disk used\"\nFROM metrics\nWHERE\n  $__timeFilter(\"time\") AND\n  name LIKE 'disk_used_percent'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "TaxiDB Cache hit ratio",
   "type": "graph",
   "description": "Cache hit ratio on Taxi DB ",
   "gridPos": { "h": 10, "w": 5, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "-- Cache Hit ratio\n-- hit = Blocks hit = number of disk block found already in the buffer cache s/t a read was not needed\n-- read = disk blocks read by data base\nSELECT hit.time, SUM(hit.value)/(SUM(hit.value) + SUM(read.value)) as cache_hit_rate\nFROM metrics_values hit \nINNER JOIN metrics_values read ON hit.time = read.time\nWHERE  hit.labels_id = 312 AND read.labels_id = 314\nGROUP BY hit.time\nORDER BY hit.time;"
    }
   ]
  }
 ]
}