{
 "title": "Taxicab Monitoring Long Term",
 "description": "Long Term Data for Taxicab DB",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Blocks Read (5min intervals)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  bucket AS \"time\",\n  metrics_labels.labels->'datname' AS metric,\n  min, avg, max\nFROM metrics_5mins\nJOIN metrics_labels ON metrics_5mins.labels_id = metrics_labels.id\nWHERE\n  $__timeFilter(bucket) AND metrics_labels.metric_name LIKE 'postgresql_pg_stat_database_blks_read'\nGROUP BY 1,2,3,4,5\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Memory Used (%)",
   "type": "graph",
   "description": "Active memory in 5min intervals",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  bucket AS \"time\",\n  min, avg, max\nFROM metrics_5mins\nWHERE\n  $__timeFilter(bucket) AND labels_id = 179\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Active Memory (5min intervals)",
   "type": "graph",
   "description": "Active memory in hourly intervals",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  bucket AS \"time\",\n  min, avg, max\nFROM metrics_5mins\nWHERE\n  $__timeFilter(bucket) AND labels_id = 153\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Available Memory (5min intervals)",
   "type": "graph",
   "description": "Active memory in hourly intervals",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  bucket AS \"time\",\n  min, avg, max\nFROM metrics_5mins\nWHERE\n  $__timeFilter(bucket) AND labels_id = 154\nORDER BY 1"
    }
   ]
  },
  {
   "title": "User CPU Breakdown (5 min intervals)",
   "type": "graph",
   "description": "User CPU Breakdown (5 min intervals)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  bucket AS \"time\",\n  min, avg, max\nFROM metrics_5mins\nWHERE\n  $__timeFilter(bucket) AND labels_id = 46\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Network Sent (5min intervals)",
   "type": "graph",
   "description": "Active memory in hourly intervals",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  bucket AS \"time\",\n  min as \"min net_out\", avg as \"avg net_out\", max as \"max net_out\"\nFROM metrics_5mins\nWHERE\n  $__timeFilter(bucket) AND labels_id = 187\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Network Received (5min intervals)",
   "type": "graph",
   "description": "bytes received",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  bucket AS \"time\",\n  min as \"min net_in\", avg as \"avg net_in\", max as \"max net_in\"\nFROM metrics_5mins\nWHERE\n  $__timeFilter(bucket) AND labels_id = 186\nORDER BY 1"
    }
   ]
  }
 ]
}