{
 "title": "Taxicab DB Monitoring For export Copy",
 "description": "Monitoring Taxicab DB Running in Timescale Cloud",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Blocks Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\", 1m),\n  metrics_labels.labels->'datname' AS metric,\n  avg(value)\nFROM metrics_values\nJOIN metrics_labels ON metrics_values.labels_id = metrics_labels.id\nWHERE\n  $__timeFilter(\"time\") AND metrics_labels.metric_name LIKE 'postgresql_pg_stat_database_blks_read'\nGROUP BY 1,2\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Disk IO Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\", 1m),\n  metrics_labels.labels->'name' AS metric,\n  avg(value)\nFROM metrics_values\nJOIN metrics_labels ON metrics_values.labels_id = metrics_labels.id\nWHERE\n  $__timeFilter(\"time\") AND metrics_labels.metric_name LIKE 'diskio_io_time'\nGROUP BY 1,2\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Blocks Hit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\", 1m),\n  metrics_labels.labels->'datname' AS metric,\n  avg(value)\nFROM metrics_values\nJOIN metrics_labels ON metrics_values.labels_id = metrics_labels.id\nWHERE\n  $__timeFilter(\"time\") AND metrics_labels.metric_name LIKE 'postgresql_pg_stat_database_blks_hit'\nGROUP BY 1,2\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Deadlocks w JOINs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\", 1m),\n  metrics_labels.metric_name::text AS metric,\n  avg(value)\nFROM metrics_values\nJOIN metrics_labels ON metrics_values.labels_id = metrics_labels.id\nWHERE\n  $__timeFilter(\"time\") AND metrics_values.labels_id = 316\nGROUP BY 1,2\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Service Status (Up or Not?)",
   "type": "heatmap",
   "description": "Is the system up at the point in time?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\", 10s),\n  avg(value) AS \"status\"\nFROM metrics_values\nWHERE\n  $__timeFilter(\"time\") AND\n  labels_id = 2259\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Active Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\", 1m),\n  avg(value) AS \"mem_active\"\nFROM metrics_values\nWHERE\n  $__timeFilter(\"time\") AND\n  labels_id = 153\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\", 1m),\n  avg(value) AS \"mem_available\"\nFROM metrics_values\nWHERE\n  $__timeFilter(\"time\") AND\n  labels_id = 154\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Memory Used (%)",
   "type": "graph",
   "description": "Percentage of Memory Used",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\", 1m),\n  avg(value) AS \"mem_used\"\nFROM metrics_values\nWHERE\n  $__timeFilter(\"time\") AND\n  labels_id = 179\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "CPU Usage Breakdown (Total)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\", 1m),\n  avg(value) AS \"system cpu usage\"\nFROM metrics_values\nWHERE\n  $__timeFilter(\"time\") AND\n  labels_id = 41\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\", 1m),\n  avg(value) AS \"user cpu usage\"\nFROM metrics_values\nWHERE\n  $__timeFilter(\"time\") AND\n  labels_id = 46\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Network Activity",
   "type": "graph",
   "description": "Bytes sent and received by DB on the network",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\", 1m),\n  avg(value) AS \"network_bytes_sent\"\nFROM metrics_values\nWHERE\n  $__timeFilter(\"time\") AND\n  labels_id = 187\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\", 1m),\n  avg(value) AS \"network_bytes_received\"\nFROM metrics_values\nWHERE\n  $__timeFilter(\"time\") AND\n  labels_id = 186\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Disk Used (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\", 1m),\n  avg(value) AS \"% disk used\"\nFROM metrics_values\nWHERE\n  $__timeFilter(\"time\") AND\n  labels_id = 57\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Connections to DB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\", 1m),\n  avg(value) AS \"defaultdb connections\"\nFROM metrics_values\nWHERE\n  $__timeFilter(\"time\") AND\n  labels_id = 296\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\", 1m),\n  avg(value) AS \"testdb2 connections\"\nFROM metrics_values\nWHERE\n  $__timeFilter(\"time\") AND\n  labels_id = 297\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Network Drops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\", 1m),\n  avg(value) AS \"network_drops_in\"\nFROM metrics_values\nWHERE\n  $__timeFilter(\"time\") AND\n  labels_id = 188\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\", 1m),\n  avg(value) AS \"network_drops_out\"\nFROM metrics_values\nWHERE\n  $__timeFilter(\"time\") AND\n  labels_id = 189\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\", 1m),\n  avg(value) AS \"deadlocks\"\nFROM metrics_values\nWHERE\n  $__timeFilter(\"time\") AND\n  labels_id = 316\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Database Sizes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\", 1m),\n  avg(value) AS \"defaultdb size\"\nFROM metrics_values\nWHERE\n  $__timeFilter(\"time\") AND\n  labels_id = 288\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\", 1m),\n  avg(value) AS \"testdb2 size\"\nFROM metrics_values\nWHERE\n  $__timeFilter(\"time\") AND\n  labels_id = 289\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}